-- 1. 매출액 컬럼 정의
-- 2. 저자별, 카테고리별로 그룹바이
-- 3. 전체 리스트 출력
-- 문제를 잘 풀어낼 수는 있겠다. 그런데, 매출액을 더 정합하게 정의하는 방법이 있을까? 

-- [내 풀이]
SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(TOTAL_SALES) AS TOTAL_SALES
FROM ( -- 매출액 컬럼 정의
    SELECT 
        B.BOOK_ID, 
        S.SALES_DATE, 
        A.AUTHOR_ID, 
        A.AUTHOR_NAME, 
        B.CATEGORY, 
        (B.PRICE * S.SALES) AS TOTAL_SALES
    FROM BOOK B
    JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID -- B레벨로
    JOIN BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID -- B레벨로
    WHERE S.SALES_DATE LIKE '2022-01%'
) ST
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY 1 ASC ,3 DESC; 


-- [추천 풀이]
SELECT 
    A.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY,
    SUM(S.SALES * B.PRICE) AS TOTAL_SALES  -
FROM BOOK B
JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
JOIN BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID
WHERE S.SALES_DATE LIKE '2022-01%'
GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY A.AUTHOR_ID ASC, B.CATEGORY DESC;
