-- 코드를 작성해주세요
SELECT E.ID, IFNULL(C.CHILD_COUNT,0) AS CHILD_COUNT
FROM 
    (SELECT PARENT_ID, COUNT(PARENT_ID) AS CHILD_COUNT
    FROM ECOLI_DATA
    GROUP BY PARENT_ID) C
RIGHT JOIN ECOLI_DATA E
ON E.ID = C.PARENT_ID
ORDER BY E.ID;