# select i.FOOD_TYPE, i.REST_ID, i.REST_NAME, i.FAVORITES
# from rest_info i
# right join 
# (select FOOD_TYPE, REST_ID, max(FAVORITES) as max_fav
# from rest_info
# group by FOOD_TYPE) m
# on i.REST_ID = m.REST_ID 
# ORDER BY i.FOOD_TYPE DESC;


SELECT RI.FOOD_TYPE, RI.REST_ID, RI.REST_NAME, RI.FAVORITES
FROM 
    (SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
    ) FT
JOIN REST_INFO RI ON FT.FOOD_TYPE = RI.FOOD_TYPE
WHERE FT.MAX_FAVORITES = RI.FAVORITES
ORDER BY RI.FOOD_TYPE DESC