SELECT RI.FOOD_TYPE, RI.REST_ID, RI.REST_NAME, RI.FAVORITES
FROM 
    (SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
    ) FT
JOIN REST_INFO RI ON FT.FOOD_TYPE = RI.FOOD_TYPE
WHERE FT.MAX_FAVORITES = RI.FAVORITES
ORDER BY RI.FOOD_TYPE DESC