
SELECT E.ID, 
CASE 
    WHEN QT.QUA = 1 THEN 'CRITICAL'
    WHEN QT.QUA = 2 THEN  'HIGH'
    WHEN QT.QUA = 3 THEN  'MEDIUM'
    ELSE 'LOW' END AS COLONY_NAME
FROM ECOLI_DATA E
JOIN 
    (SELECT ID, 
        NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS QUA
    FROM ECOLI_DATA) QT ON E.ID = QT.ID
ORDER BY E.ID;
