# -- 코드를 입력하세요
# SELECT 
#     RI.REST_ID, 
#     RI.REST_NAME, 
#     RI.FOOD_TYPE, 
#     RI.FAVORITES, 
#     RI.ADDRESS, 
#     ROUND(AVG(RR.REVIEW_SCORE),2) AS SCORE
# FROM 
#     (SELECT *
#     FROM REST_INFO
#     WHERE ADDRESS LIKE '%서울%') RI
# JOIN REST_REVIEW RR
# ON RI.REST_ID = RR.REST_ID
# GROUP BY RI.REST_ID
# ORDER BY AVG(RR.REVIEW_SCORE) DESC, RI.FAVORITES DESC;

-- 서브쿼리까지 쓸 필요 없음;;

SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, 
ROUND(AVG(R.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO I 
JOIN REST_REVIEW R
ON I.REST_ID = R.REST_ID
WHERE I.ADDRESS LIKE '서울%'
GROUP BY I.REST_ID
ORDER BY SCORE DESC, I.FAVORITES DESC;
