-- 코드를 입력하세요,
SELECT 
    CAR_ID, 
    ROUND(AVG(DATEDIFF(END_DATE, START_DATE) + 1),1) AS AVERAGE_DURATION
FROM 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY
    CAR_ID
HAVING 
    AVG(DATEDIFF(END_DATE, START_DATE) + 1) >= 7
ORDER BY 
    AVERAGE_DURATION DESC, 
    CAR_ID DESC;

-- [참고]
-- 절댓값 구하기 : ABS(-7)
-- DATEDIFF(A,B) : a - b , DAY 차이 정수 계산
-- ROUND(컬럼, 2) : 2번째자리**까지** 반올림!