SELECT COUNT(*) AS FISH_COUNT, N.FISH_NAME
FROM FISH_INFO I LEFT JOIN FISH_NAME_INFO N ON I.FISH_TYPE = N.FISH_TYPE
GROUP BY N.FISH_NAME
ORDER BY FISH_COUNT DESC;

-- 주의 : '종류 별' 구하는 것인데, GROUP BY FISH_TYPE(INTEGER타입)이 오류인 이유
