-- 코드를 작성해주세요

SELECT ID,
CASE 
WHEN SIZE_OF_COLONY <= 100 THEN 'LOW'
WHEN SIZE_OF_COLONY > 100 AND SIZE_OF_COLONY <= 1000 THEN 'MEDIUM'
ELSE 'HIGH' END AS SIZE
FROM ECOLI_DATA
ORDER BY ID ASC

-- CASE절 사용 시 주의 점 : SELECT 절의 하나의 컬럼이므로 앞에 콤마로 필수