-- 코드를 작성해주세요

# SELECT 
#     CONCAT(QUARTER(DIFFERENTIATION_DATE), 'Q') AS QUARTER, 
#     COUNT(*) AS ECOLI_COUNT
# FROM ECOLI_DATA 
# GROUP BY QUARTER(DIFFERENTIATION_DATE) 
# ORDER BY QUARTER(DIFFERENTIATION_DATE) ASC;
-- 실행X 이유
-- SELECT에서는 CONCAT(QUARTER(...),'Q') 형태인데
-- GROUP BY는 QUARTER(...)만 사용하여 표현식이 서로 다름
-- ONLY_FULL_GROUP_BY 모드에서는 SELECT의 표현식과 GROUP BY 표현식이
-- 정확히 동일하거나 함수적으로 종속되어야 함

# SELECT 
#     CONCAT(QUARTER(DIFFERENTIATION_DATE), 'Q') AS  QUARTER, 
#     COUNT(QUARTER(DIFFERENTIATION_DATE)) AS ECOLI_COUNT
# FROM ECOLI_DATA 
# GROUP BY QUARTER(DIFFERENTIATION_DATE) 
# ORDER BY QUARTER(DIFFERENTIATION_DATE) ASC;
-- 실행x 이유
-- 1. COUNT(QUARTER(...))는 의미상 문제는 없지만 불필요한 연산
-- 2. QUARTER(...)는 NULL이 아니므로 COUNT(*)와 동일하게 동작
-- 3. 일반적으로 집계는 COUNT(*) 사용이 표준적이고 효율적

SELECT
    CONCAT(QUARTER(DIFFERENTIATION_DATE),'Q') AS QUARTER,
    COUNT(*) AS ECOLI_COUNT
FROM ECOLI_DATA
GROUP BY QUARTER
ORDER BY QUARTER ASC;
