-- 코드를 입력하세요
SELECT P.ID, P.NAME, P.HOST_ID
FROM 
    (SELECT HOST_ID, COUNT(HOST_ID)
    FROM PLACES
    GROUP BY HOST_ID
    HAVING COUNT(HOST_ID) >= 2) H
JOIN PLACES P
ON H.HOST_ID = P.HOST_ID
ORDER BY P.ID;
