# -- 코드를 입력하세요
# SELECT P.PRODUCT_ID, P.PRODUCT_NAME, P.PRICE * O.AMOUNT AS TOTAL_SALES
# FROM FOOD_PRODUCT P JOIN FOOD_ORDER O
# ON P.PRODUCT_ID = O.PRODUCT_ID
# WHERE DATE_FORMAT(PRODUCE_DATE, '%Y-%m') = '2022-05'
# GROUP BY P.PRODUCT_NAME
# ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID ASC 
# -- 제대로 컬럼 안읽어서 생긴 문제임

SELECT p.PRODUCT_ID, p.PRODUCT_NAME, P.PRICE * SUM(O.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT P
    JOIN FOOD_ORDER O 
    ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE DATE_FORMAT(O.PRODUCE_DATE, '%Y-%m') = '2022-05'
GROUP BY P.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID ASC 

