-- SOL1 : 서브쿼리를 사용 (WHERE절로 필터링) - 제출 버전
SELECT *
FROM (
  SELECT B.WRITER_ID AS USER_ID, U.NICKNAME, SUM(B.PRICE) AS TOTAL_SALES
  FROM USED_GOODS_BOARD B JOIN USED_GOODS_USER U ON B.WRITER_ID = U.USER_ID	
  WHERE B.STATUS = 'DONE'
  GROUP BY B.WRITER_ID) AS T
WHERE T.TOTAL_SALES >= 700000
ORDER BY T.TOTAL_SALES ASC;

-- * 가독성 보완한 버전


  -- SOL2 HAVING 사용 (HAVING으로 집계 사용)
SELECT B.WRITER_ID AS USER_ID, U.NICKNAME, SUM(B.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD B
JOIN USED_GOODS_USER U ON B.WRITER_ID = U.USER_ID
WHERE B.STATUS = 'DONE'
GROUP BY B.WRITER_ID, U.NICKNAME
HAVING SUM(B.PRICE) >= 700000
ORDER BY TOTAL_SALES ASC;
-- [주의] SELECT에 집계 아닌 컬럼이 있으면 → GROUP BY에 다 넣어라
