-- SOL1 : 서브쿼리를 사용 (WHERE절로 필터링) - 제출 버전
SELECT T.USER_ID, T.NICKNAME, T.TOTAL_SALES
FROM (
  SELECT B.WRITER_ID AS USER_ID, U.NICKNAME, SUM(B.PRICE) AS TOTAL_SALES
  FROM USED_GOODS_BOARD B JOIN USED_GOODS_USER U ON B.WRITER_ID = U.USER_ID	
  WHERE B.STATUS = 'DONE'
  GROUP BY B.WRITER_ID) AS T
WHERE T.TOTAL_SALES >= 700000
ORDER BY T.TOTAL_SALES ASC;
-- [참고] 실무에서는 메인 쿼리 SELECT *보다는, 컬럼명을 명시할 것
-- [주의] JOIN하는 두 테이블의 컬럼명이 중복되지 않더라도, 해당 컬럼의 테이블명을 작성해줄 것

  -- SOL2 HAVING 사용 (HAVING으로 집계 사용)
SELECT 
  B.WRITER_ID AS USER_ID,
  U.NICKNAME,
  SUM(B.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD B
JOIN USED_GOODS_USER U 
  ON B.WRITER_ID = U.USER_ID
WHERE B.STATUS = 'DONE'
GROUP BY B.WRITER_ID, U.NICKNAME
HAVING SUM(B.PRICE) >= 700000
ORDER BY TOTAL_SALES ASC;
-- [주의] SELECT에 집계 아닌 컬럼이 있으면 → GROUP BY에 다 넣어라
-- GROUP BY USER_ID
-- HAVING SUM(PRICE) > 700000;



