# SELECT *
# FROM (SELECT B.WRITER_ID AS USER_ID, U.NICKNAME, TOTAL_SALES
# FROM USED_GOODS_BOARD B JOIN USED_GOODS_USER U ON B.WRITER_ID = U.USER_ID	
# WHERE B.STATUS = 'DONE'
# GROUP BY B.WRITER_ID
# HAVING SUM(B.PRICE) AS TOTAL_SALES) AS T
# WHERE T.TOTAL_SALES >= 700000
# ORDER BY T.TOTAL_SALES DESC

SELECT *
FROM (SELECT B.WRITER_ID AS USER_ID, U.NICKNAME, SUM(B.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD B JOIN USED_GOODS_USER U ON B.WRITER_ID = U.USER_ID	
WHERE B.STATUS = 'DONE'
GROUP BY B.WRITER_ID) AS T
WHERE T.TOTAL_SALES >= 700000
ORDER BY T.TOTAL_SALES ASC


-- WHERE (SELECT WRITER_ID, SUM(PRICE) FROM USED_GOODS_BOARD GROUP BY WRITER_ID)

-- 질문1 : INNER JOIN 괜찮은지?