-- 코드를 입력하세요
SELECT I.ANIMAL_ID, O.NAME
FROM ANIMAL_INS I LEFT JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.DATETIME > O.DATETIME
ORDER BY I.DATETIME ASC

-- [특징] '보호시작일(I.DATETIME)'보다 '입양일(O.DATETIME)'이 더 빠른 : WHERE I.DATETIME > O.DATETIME
-- * LFET JOIN 대신, (INNER) JOIN 사용해도 됨
