SELECT 
    MONTH(START_DATE) AS MONTH, 
    CAR_ID, 
    COUNT(CAR_ID) AS RECORDS
FROM 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE 
    CAR_ID IN 
        (SELECT car_id
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
        GROUP BY CAR_ID
        HAVING COUNT(CAR_ID) >= 5)
    AND START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY 
    DATE_FORMAT(START_DATE, '%Y-%m'), CAR_ID
ORDER BY 
    MONTH ASC, 
    CAR_ID DESC;

-- 1. 
-- 특정 월의 총 대여 횟수가 0인 경우에는 결과에서 제외
-- 서브쿼리를 무조건 써야함

-- 2. 
-- 정답 : WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
-- 오답 : BETWEEN MONTH(START_DATE) = 8 AND BETWEEN MONTH(START_DATE) = 10
-- 오답조차 수정 : WHERE MONTH(START_DATE) BETWEEN 8 AND 10
-- 오답 이유 : 연도를 고려하지 않기 떄문임