SELECT E.YEAR, M.MAX_SIZE - E.SIZE_OF_COLONY AS YEAR_DEV, E.ID
FROM
    (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)) M
JOIN 
    (SELECT ID, YEAR(DIFFERENTIATION_DATE) AS YEAR, SIZE_OF_COLONY
    FROM ECOLI_DATA) E
ON M.YEAR = E.YEAR 
ORDER BY 1,2;

# 삽질 로그들... 
# SELECT *
# FROM ECOLI_DATA ED
# LEFT JOIN 
#     (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY)
#     FROM ECOLI_DATA
#     GROUP BY YEAR(DIFFERENTIATION_DATE)) MT
# ON ED.SIZE_OF_COLONY = MT.SIZE_OF_COLONY

# SELECT
# FROM 
# (SELECT E.ID, 
#     YEAR(DIFFERENTIATION_DATE), 
#     RANK() OVER (PARTITION BY YEAR(DIFFERENTIATION_DATE) ORDER BY SIZE_OF_COLONY DESC) AS RNK, 
#     SIZE_OF_COLONY
# FROM ECOLI_DATA) R
# JOIN ECOLI_DATA E
# ON R.ID = E.ID






