# -- VER1 (WHERE)
# SELECT COUNT(*) AS FISH_COUNT
# FROM FISH_INFO F 
# JOIN FISH_NAME_INFO N 
# ON F.FISH_TYPE = N.FISH_TYPE
# WHERE N.FISH_NAME = 'BASS' OR N.FISH_NAME = 'SNAPPER';

-- VER2 (IN)
SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO FI
JOIN FISH_NAME_INFO NI
ON FI.FISH_TYPE = NI.FISH_TYPE
WHERE NI.FISH_NAME IN ('BASS', 'SNAPPER');