-- SOL1 
SELECT ID, FISH_NAME, LENGTH
FROM 
    (SELECT 
        I.ID, 
        I.FISH_TYPE, 
        N.FISH_NAME,
        I.LENGTH,
        RANK() OVER (PARTITION BY I.FISH_TYPE ORDER BY LENGTH DESC) AS RNK
    FROM FISH_INFO I -- M집합
    JOIN FISH_NAME_INFO N -- 1집합
    ON I.FISH_TYPE = N.FISH_TYPE -- I레벨(M집합)
    WHERE LENGTH IS NOT NULL -- 처리 필요 없나? 어떻게 할 것인지 ! -> 이 문제에서는 NULL처리가 필요 없음
) RTB
WHERE RNK = 1
ORDER BY 1;


-- SOL2) MAX 윈도우 -> 문제 기준 더 직관적 + 안정적
WITH MAX_TB AS 
(
SELECT 
    I.ID, 
    I.FISH_TYPE, 
    N.FISH_NAME,
    I.LENGTH,
    MAX(LENGTH) OVER (PARTITION BY FISH_TYPE) AS MAX_LENGTH
FROM FISH_INFO I -- M집합
JOIN FISH_NAME_INFO N -- 1집합
ON I.FISH_TYPE = N.FISH_TYPE -- I레벨(M집합)
)
SELECT ID, FISH_NAME, LENGTH
FROM MAX_TB
WHERE MAX_LENGTH = LENGTH
ORDER BY 1
