SELECT ID, FISH_NAME, LENGTH
FROM 
    (SELECT 
        I.ID, 
        I.FISH_TYPE, 
        N.FISH_NAME,
        I.LENGTH,
        RANK() OVER (PARTITION BY I.FISH_TYPE ORDER BY LENGTH DESC) AS RNK
    FROM FISH_INFO I -- M집합
    JOIN FISH_NAME_INFO N -- 1집합
    ON I.FISH_TYPE = N.FISH_TYPE -- I레벨(M집합)
    WHERE LENGTH IS NOT NULL -- 처리 필요 없나? 어떻게 할 것인지 !
) RTB
WHERE RNK = 1
ORDER BY 1;


# SELECT I.ID, A.FISH_TYPE, A.FISH_NAME
# FROM 
# (SELECT I.ID, N.FISH_NAME, I.LENGTH, MAX(LENGTH) OVER (PARTITION BY I.FISH_TYPE) AS MAX_LENGTH
# FROM FISH_INFO I -- M집합
# JOIN FISH_NAME_INFO N -- 1집합
# ON I.FISH_TYPE = N.FISH_TYPE) A-- I레벨(M집합)
# GROUP BY A.FISH_NAME
