-- 코드를 작성해주세요

# 목적 : 2022년도 한해 평가 점수가 가장 높은 사원

SELECT K.SCORE, H.EMP_NO, H.EMP_NAME, H.POSITION, H.EMAIL
FROM (SELECT EMP_NO, SUM(SCORE) AS SCORE
FROM HR_GRADE
GROUP BY EMP_NO
ORDER BY SUM(SCORE) DESC LIMIT 1) K
LEFT JOIN HR_EMPLOYEES H
ON K.EMP_NO = H.EMP_NO

