-- 코드를 입력하세요
-- SOL1) CTE사용
# WITH MAX_TABLE AS
#     (SELECT max(VIEWS)
#     FROM USED_GOODS_BOARD)
# SELECT 
# FROM USED_GOODS_FILE
# MAX_TABLE

-- SOL2) 
SELECT 
    CONCAT('/home/grep/src/', F.BOARD_ID, '/', F.FILE_ID, F.FILE_NAME, F.FILE_EXT) AS FILE_PATH
FROM 
    (SELECT *
    FROM USED_GOODS_BOARD
    WHERE VIEWS = (SELECT max(VIEWS) FROM USED_GOODS_BOARD)
    ) T
JOIN USED_GOODS_FILE F 
ON F.BOARD_ID = T.BOARD_ID
ORDER BY F.FILE_ID DESC;