-- sol1)
# SELECT M.CATEGORY, M.MAX_PRICE, P.PRODUCT_NAME
# FROM FOOD_PRODUCT P 
# JOIN 
# (SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
# FROM FOOD_PRODUCT
# WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
# GROUP BY CATEGORY) M 
# ON P.CATEGORY = M.CATEGORY
# WHERE M.MAX_PRICE = P.PRICE
# ORDER BY MAX_PRICE DESC;
-- 중요한 생각 흐름
-- 1. 먼저 카테고리별 최고 가격을 구한다.
-- 2. 그 최고 가격과 같은 PRICE를 가진 행을 찾는다.

-- SOL2) 윈도우 함수
SELECT M.CATEGORY, M.PRICE AS MAX_PRICE, M.PRODUCT_NAME
FROM 
(SELECT *, RANK() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS RNK
FROM FOOD_PRODUCT) M
WHERE CATEGORY IN ('과자', '국', '김치', '식용유') AND RNK = 1
ORDER BY MAX_PRICE DESC;
